# Generated by Django 3.0.3 on 2020-08-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Short_desc', models.TextField()),
                ('Intro', models.TextField()),
                ('Technology', models.CharField(blank=True, default='None', max_length=300)),
                ('Module', models.CharField(blank=True, default='None', max_length=300)),
                ('Github_link', models.CharField(blank=True, default='None', max_length=300)),
            ],
        ),
    ]
