# Generated by Django 3.0.3 on 2020-08-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='image',
            field=models.FileField(upload_to='project/media/project_image/'),
        ),
    ]
