# Generated by Django 3.0.3 on 2020-08-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200809_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='image',
            field=models.FileField(upload_to='project/static/project/media/project_image/'),
        ),
    ]
