# Generated by Django 3.0.3 on 2020-08-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200809_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='image',
            field=models.FileField(upload_to='project_image/'),
        ),
    ]
